"../rtl/uvml_if/hs_if.sv"
"../rtl/uvml_if/stream_if.sv"
"../rtl/uvml_if/axis_if.sv"
"../rtl/uvml_if/axilite_if.sv"
"../rtl/uvml_if/axi_if.sv"
"../rtl/uvml_if/ram_if.sv"

"../rtl/reg_slice.sv"
"../rtl/reg_axis.sv"
"../rtl/reg_axi.sv"
"../rtl/reg_axilite.sv"
"../rtl/sram_sdp.sv"
"../rtl/ram_fifo.sv"
"../rtl/stream_fifo.sv"
"../rtl/stream_pkt_fifo.sv"